### ISSUE TITLE
Directory API Call Error

### ISSUE THREAD

**Issue by CB-korey** [Cloudbakers/agm#9]
Hey,

When running the command: agm directory users list --domain levelup-mail.com
I am receiving: HttpError 403 when requesting https://www.googleapis.com/admin/directory/v1/users?fields=%2A&domain=levelup-mail.com&alt=json returned \"Not Authorized to access this resource/api\"

also running: agm directory users list
I am receiving: HttpError 400 when requesting https://www.googleapis.com/admin/directory/v1/users?fields=%2A&alt=json returned \"Bad Request\"

**Comment by alexwennerberg** [comment]
These API commands are weird -- you have to specify the customer with the flag "--customer my_customer"

**Comment by alexwennerberg** [comment]
you also may have to impersonate the admin user with the --user flag. Try that out. Closing this issue as it is related to the Google API not AGM itself.
